site_name: ZeroTwentyFifty - PACT Methodology

theme:
  name: "material"

plugins:
  - mkdocstrings

repo_name: ZeroTwentyFifty/pact_methodology
repo_url: https://github.com/ZeroTwentyFifty/pact_methodology
site_author: ZeroTwentyFifty
site_description: Documentation for ZeroTwentyFifty's PACT Methodology
edit_uri: ""

nav:
  - Introduction: "README.md"
  - Developer Contribution Guide: "developer_contribution_guide.md"
  - Reference:
    - Overview: "reference.md" 
    - Carbon Footprint:
      - Carbon Footprint: "reference/carbon_footprint.md"
      - Geographical Scope: "reference/carbon_footprint/geographical_scope.md"
      - Region or Subregion: "reference/carbon_footprint/region_or_subregion.md"
      - Reference Period: "reference/carbon_footprint/reference_period.md"
      - Biogenic Accounting Methodology: "reference/carbon_footprint/biogenic_accounting_methodology.md"
      - Characterization Factors: "reference/carbon_footprint/characterization_factors.md"
      - Cross Sectoral Standard Set: "reference/carbon_footprint/cross_sectoral_standard_set.md"
      - Cross Sectoral Standard: "reference/carbon_footprint/cross_sectoral_standard.md"
      - Declared Unit: "reference/carbon_footprint/declared_unit.md"
      - Emission Factor DS Set: "reference/carbon_footprint/emission_factor_ds_set.md"
      - Emission Factor DS: "reference/carbon_footprint/emission_factor_ds.md"
      - Product or Sector Specific Rule Operator: "reference/carbon_footprint/product_or_sector_specific_rule_operator.md"
      - Product or Sector Specific Rule Set: "reference/carbon_footprint/product_or_sector_specific_rule_set.md"
      - Product or Sector Specific Rule: "reference/carbon_footprint/product_or_sector_specific_rule.md"
    - Product Footprint:
      - Product Footprint: "reference/product_footprint.md"
      - CPC: "reference/product_footprint/cpc.md"
      - Product ID List: "reference/product_footprint/product_id_list.md"
      - Company ID List: "reference/product_footprint/company_id_list.md"
      - Validity Period: "reference/product_footprint/validity_period.md"
      - Version: "reference/product_footprint/version.md"
      - Status: "reference/product_footprint/status.md"
      - ID: "reference/product_footprint/id.md"
    - Assurance: "reference/assurance.md"
    - Data Model Extension: "reference/data_model_extension.md"
    - Data Quality Indicators: "reference/data_quality_indicators.md"
    - Data Quality Rating: "reference/data_quality_rating.md"
    - URN: "reference/urn.md"
